CREATE OR REPLACE VIEW V_GENERATED_DATES AS
	(SELECT
		DATES::date AS GENERATED_DATE
	FROM
		generate_series('2022-01-01'::date, '2022-01-31', '1 days') AS DATES
	ORDER BY
		GENERATED_DATE);

SELECT
	*
FROM
	V_GENERATED_DATES